### PR TITLE
Supress make echoes

### PR DESCRIPTION
**Pull request by varas**
Supress Make echoes to avoid noisy cli output.

Detailed steps should be at least optional, not mandatory, we just need to know when something goes wrong.

### Author

- [x] add a risk label after carefully considering the "blast radius" of your changes
- [x] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x] assign at least one reviewer

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by mariomac** [comment]
Not a strong opinion here. I observed that all the makefiles of the team have echoes. Any argument to remove them?

**Comment by varas** [comment]
I think detailed steps should be optional, when working we are interested on output details when something goes wrong.

That's my opinion, so feel free to close if not agree.

**Comment by mariomac** [comment]
Not strong opinion. Let's see what @smoya thinks about.

**Comment by smoya** [comment]
I agree removing them since the value they add is not comparable to the noise that they add when reading the Makefile.

**Comment by varas** [comment]
I could add a `VERBOSE` variable to keep current verbose output in case it's required for ie: CI

**Pull request merged**
